---
- hosts: all
  tasks:
     - name: Ping All Servers
       action: ping
     - debug: msg="Server says hello"

- hosts: dev
  name: DEV servers play
  tasks:
     - debug: msg="Dev servers says hello"
