---
- hosts: qa
  tasks:
     - name: Kernel
       debug: msg="{{ansible_kernel}}"
     - name: Hostname
       debug: msg="{{ansible_hostname}}"
     - name: Distribution
       debug: msg="{{ansible_distribution}}"
     - debug: var=ansible_architecture
     - debug: var=hostvars
     - debug: var=inventory_hostname
     - debug: var=ansible_domain
     - debug: var=groups
     - debug: var=group_names
